# Generated by Django 5.2.5 on 2025-08-15 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentvideo',
            old_name='date_uploaded',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='date_uploaded',
            new_name='createdAt',
        ),
    ]
