# Generated by Django 5.2.5 on 2025-08-22 20:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercommentrelation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='uservideorelation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='watchhistory',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='usercommentrelation',
            constraint=models.UniqueConstraint(fields=('comment', 'user'), name='unique_comment_user_relation'),
        ),
        migrations.AddConstraint(
            model_name='uservideorelation',
            constraint=models.UniqueConstraint(fields=('video', 'user'), name='unique_video_user_relation'),
        ),
        migrations.AddConstraint(
            model_name='watchhistory',
            constraint=models.UniqueConstraint(fields=('viewer', 'video'), name='unique_viewer_video_history'),
        ),
    ]
