# Generated by Django 5.2.5 on 2025-08-15 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_rename_date_uploaded_commentvideo_createdat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='src',
        ),
    ]
