# Generated by Django 5.2.5 on 2025-08-15 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_rename_video_video_src'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentvideo',
            old_name='author',
            new_name='channel',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='author',
            new_name='channel',
        ),
    ]
