# Generated by Django 5.2.5 on 2025-08-15 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_rename_author_commentvideo_channel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='search_embedding',
        ),
    ]
