# Generated by Django 5.2.5 on 2025-08-19 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_remove_video_search_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentvideo',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='videos.commentvideo', verbose_name='Родительский комментарий'),
        ),
    ]
