# Generated by Django 5.2.5 on 2025-08-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_commentvideo_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentvideo',
            name='baseStars',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Количество звёзд'),
        ),
    ]
