# Generated by Django 5.2.5 on 2025-08-19 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_commentvideo_basestars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentvideo',
            old_name='instance',
            new_name='video',
        ),
    ]
