# Generated by Django 5.2.5 on 2025-08-19 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_rename_instance_commentvideo_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentvideo',
            old_name='content',
            new_name='text',
        ),
    ]
