# Generated by Django 4.2.14 on 2024-08-08 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAdditional',
        ),
    ]
