version: '3.8'

services:
  jupyter:
    build: 
      context: .
    container_name: jupyter-tensorflow-gpu
    restart: always
    ports:
      - "8888:8888"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./notebooks:/tf/notebooks
      - ./config.py:/root/.jupyter/jupyter_notebook_config.py
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

    command: jupyter notebook --notebook-dir=/tf/notebooks --ip=0.0.0.0 --no-browser --allow-root
