services:
  web:
    build: 
      context: .
    environment:
      DB_NAME: gtdb
      DB_USER: gleb
      DB_PASS: 1234
      DB_HOST: db  # This is the service name defined in docker-compose.yml
      DB_PORT: 5432
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - db
    command: > 
      sh -c "python manage.py runserver 0.0.0.0:8000"
  

  db:
    image: postgres:16.3-alpine3.20
    environment:
      POSTGRES_DB: gtdb
      POSTGRES_USER: gleb
      PGPORT : 5432
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.5-alpine
    hostname: redis
  worker:
    build: 
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./:/app
    links: 
      - redis
    depends_on:
      - redis
  flower:
    build: 
      context: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - ./:/app
    links: 
      - redis
    ports:
      - "5555:5555"
    depends_on:
      - redis

volumes:
  postgres_data: