# Generated by Django 4.2.16 on 2025-08-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_embeddings',
            field=models.JSONField(blank=True, null=True, verbose_name='Кластеры эмбеддингов'),
        ),
    ]
