# Generated by Django 5.2.5 on 2025-08-15 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_user_user_embeddings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='stars_count',
            new_name='baseStars',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='profile_description',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='subs_count',
            new_name='subscriberCount',
        ),
    ]
