# Generated by Django 5.2.5 on 2025-08-21 21:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_rename_stars_count_user_basestars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joinedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата регистрации'),
            preserve_default=False,
        ),
    ]
