name: django-app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  init:
    runs-on: self-hosted
    steps:
     - name: Installing docker-compose
       run: docker ps
 