# Generated by Django 4.2.14 on 2024-07-14 00:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.aggregates
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=64, verbose_name='Название')),
                ('description', models.TextField(max_length=1024, verbose_name='Описание')),
                ('img', models.ImageField(null=True, upload_to='images_uploaded', verbose_name='Превью')),
                ('video', models.FileField(null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='Видео')),
                ('views', models.PositiveBigIntegerField(default=0, verbose_name='Количество просмотров')),
                ('stars_count', models.PositiveBigIntegerField(default=django.db.models.aggregates.Count('rates'), verbose_name='Количество звёзд')),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='RateVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.BooleanField(choices=[(0, 'Без оценки'), (1, 'С оценкой')], default=0, verbose_name='Оценка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='video_manager.video', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Рейтинг видео',
                'verbose_name_plural': 'Рейтинг видео',
            },
        ),
        migrations.CreateModel(
            name='CommentVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_manager.video', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Комментарий под видео',
                'verbose_name_plural': 'Коментарии под видео',
            },
        ),
    ]
