# Generated by Django 5.2.5 on 2025-08-15 19:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_users_sub',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='author',
            new_name='channel',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('subscriber', 'channel'), name='unique_users_sub'),
        ),
    ]
