name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Docker Compose
      run: sudo apt-get update && sudo apt-get install -y docker-compose

    - name: Create .env file inside GlebTube
      run: |
        mkdir -p GlebTube
        echo "DB_NAME=gleb_db" >> GlebTube/.env
        echo "DB_USER=gleb" >> GlebTube/.env
        echo "DB_PASS=1234" >> GlebTube/.env
        echo "DB_HOST=db" >> GlebTube/.env
        echo "DB_PORT=5432" >> GlebTube/.env

    - name: Build the Docker Compose
      run: docker-compose -f ./GlebTube/docker-compose.yml build
