name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      -name: Installing docker-compose
      run apt install docker-compose -y
  build:
    needs: init
    runs-on: ubuntu-latest
    steps:
    - name: Building dockerfile
      run: docker build ./GlebTube
