name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  init:
    runs-on: self-hosted
    steps:
     - name: Installing docker-compose
       run: apt install docker-compose
  build:
    runs-on: self-hosted
    needs: init
    steps:
      -name: Fetching data...
      run: git fetch && git pull
      -name: Building docker-compose
      run: docker-compose -f ./GlebTube/docker-compose.yml build 
